# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Docs"
  url = "/docs/master"
  weight = 50

[[main]]
  name = "REST APIs"
  url = "/docs/master/rest-api"

########## docs menu items #########

[[docs]]
  identifier = "docs"
  name = "Versions"
  url = "#"
  weight = 10

[[docs]]
  parent = "docs"
  name = "master"
  url = "master"
  weight = 10

[[master]]
  name = "Contents"
  url = "#"
  weight = 30

[[master]]
  name = "Quickstart"
  url = "#"
  weight = 20

[[rest-api]]
  name = "REST APIs"
  url = "#"
  weight = 30
